/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type StatsByTumorType struct {

	// Median Age at Dx
	AgeAtDx int32 `json:"ageAtDx,omitempty"`

	// Frequency Of Biallelic
	FBiallelic float64 `json:"fBiallelic,omitempty"`

	// Frequency Of Cancer Type Count
	FCancerTypeCount float64 `json:"fCancerTypeCount,omitempty"`

	// Hrd Score
	HrdScore *HrdScore `json:"hrdScore,omitempty"`

	// Msi Score
	MsiScore float64 `json:"msiScore,omitempty"`

	// Number Of Cancer Type Count
	NCancerTypeCount int32 `json:"nCancerTypeCount,omitempty"`

	// Number Of Germline Homozygous Per Tumor Type
	NumberOfGermlineHomozygous int32 `json:"numberOfGermlineHomozygous,omitempty"`

	// Number of Variants with Signature
	NumberWithSig int32 `json:"numberWithSig,omitempty"`

	// Median TMB
	Tmb float64 `json:"tmb,omitempty"`

	// Tumor Type
	TumorType string `json:"tumorType,omitempty"`
}
