/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TranscriptConsequenceSummary struct {

	// Alt Amino Acid
	AminoAcidAlt string `json:"aminoAcidAlt,omitempty"`

	// Reference Amino Acid
	AminoAcidRef string `json:"aminoAcidRef,omitempty"`

	// Amino acids change
	AminoAcids string `json:"aminoAcids,omitempty"`

	// Codon change
	CodonChange string `json:"codonChange,omitempty"`

	// Consequence terms (comma separated)
	ConsequenceTerms string `json:"consequenceTerms,omitempty"`

	// Entrez gene id
	EntrezGeneId string `json:"entrezGeneId,omitempty"`

	Exon string `json:"exon,omitempty"`

	// HGVSc
	Hgvsc string `json:"hgvsc,omitempty"`

	// HGVSp
	Hgvsp string `json:"hgvsp,omitempty"`

	// HGVSp short
	HgvspShort string `json:"hgvspShort,omitempty"`

	// Hugo gene symbol
	HugoGeneSymbol string `json:"hugoGeneSymbol,omitempty"`

	IsVue bool `json:"isVue,omitempty"`

	// Polyphen Prediction
	PolyphenPrediction string `json:"polyphenPrediction,omitempty"`

	// Polyphen Score
	PolyphenScore float64 `json:"polyphenScore,omitempty"`

	// Protein position (start and end)
	ProteinPosition *IntegerRange `json:"proteinPosition,omitempty"`

	// RefSeq id
	RefSeq string `json:"refSeq,omitempty"`

	// Sift Prediction
	SiftPrediction string `json:"siftPrediction,omitempty"`

	// Sift Score
	SiftScore float64 `json:"siftScore,omitempty"`

	// Transcript id
	TranscriptId string `json:"transcriptId"`

	// Uniprot ID
	UniprotId string `json:"uniprotId,omitempty"`

	// Variant classification
	VariantClassification string `json:"variantClassification,omitempty"`
}
