/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Homozygotes struct {

	Hom int32 `json:"hom"`

	HomAfr int32 `json:"hom_afr"`

	HomAmr int32 `json:"hom_amr"`

	HomAsj int32 `json:"hom_asj"`

	HomEas int32 `json:"hom_eas"`

	HomFin int32 `json:"hom_fin"`

	HomNfe int32 `json:"hom_nfe"`

	HomOth int32 `json:"hom_oth"`

	HomSas int32 `json:"hom_sas"`
}
