/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SignalMutation struct {

	// Biallelic Counts by Tumor Type
	BiallelicCountsByTumorType []CountByTumorType `json:"biallelicCountsByTumorType,omitempty"`

	// Chromosome
	Chromosome string `json:"chromosome,omitempty"`

	// Counts by Tumor Type
	CountsByTumorType []CountByTumorType `json:"countsByTumorType,omitempty"`

	// End Position
	EndPosition int64 `json:"endPosition,omitempty"`

	// General Population Stats
	GeneralPopulationStats *GeneralPopulationStats `json:"generalPopulationStats,omitempty"`

	// Hugo Gene Symbol
	HugoGeneSymbol string `json:"hugoGeneSymbol,omitempty"`

	// Msk Expert Review
	MskExperReview bool `json:"mskExperReview,omitempty"`

	// Mutation Status
	MutationStatus string `json:"mutationStatus,omitempty"`

	OverallNumberOfGermlineHomozygous int32 `json:"overallNumberOfGermlineHomozygous,omitempty"`

	// Pathogenic
	Pathogenic string `json:"pathogenic,omitempty"`

	// Penetrance
	Penetrance string `json:"penetrance,omitempty"`

	// QC Pass Counts by Tumor Type
	QcPassCountsByTumorType []CountByTumorType `json:"qcPassCountsByTumorType,omitempty"`

	// Reference Allele
	ReferenceAllele string `json:"referenceAllele,omitempty"`

	// Start Position
	StartPosition int64 `json:"startPosition,omitempty"`

	// Stats By Tumor Type
	StatsByTumorType []StatsByTumorType `json:"statsByTumorType,omitempty"`

	// Variant Allele
	VariantAllele string `json:"variantAllele,omitempty"`
}
