# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tempo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tempo.proto',
  package='cbiomodels',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btempo.proto\x12\ncbiomodels\"\x8c\x01\n\x05\x45vent\x12\x12\n\nchromosome\x18\x01 \x01(\t\x12\x15\n\rstartPosition\x18\x02 \x01(\x05\x12\x13\n\x0b\x65ndPosition\x18\x03 \x01(\x05\x12\x11\n\trefAllele\x18\x04 \x01(\t\x12\x17\n\x0ftumorSeqAllele1\x18\x05 \x01(\t\x12\x17\n\x0ftumorSeqAllele2\x18\x06 \x01(\t\"z\n\x0cTempoMessage\x12\x13\n\x0b\x63moSampleId\x18\x01 \x01(\t\x12\x19\n\x11normalCmoSampleId\x18\x02 \x01(\t\x12\x17\n\x0fpipelineVersion\x18\x03 \x01(\t\x12!\n\x06\x65vents\x18\x04 \x03(\x0b\x32\x11.cbiomodels.Eventb\x06proto3'
)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='cbiomodels.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chromosome', full_name='cbiomodels.Event.chromosome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startPosition', full_name='cbiomodels.Event.startPosition', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endPosition', full_name='cbiomodels.Event.endPosition', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='refAllele', full_name='cbiomodels.Event.refAllele', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tumorSeqAllele1', full_name='cbiomodels.Event.tumorSeqAllele1', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tumorSeqAllele2', full_name='cbiomodels.Event.tumorSeqAllele2', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=168,
)


_TEMPOMESSAGE = _descriptor.Descriptor(
  name='TempoMessage',
  full_name='cbiomodels.TempoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmoSampleId', full_name='cbiomodels.TempoMessage.cmoSampleId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='normalCmoSampleId', full_name='cbiomodels.TempoMessage.normalCmoSampleId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pipelineVersion', full_name='cbiomodels.TempoMessage.pipelineVersion', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='events', full_name='cbiomodels.TempoMessage.events', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=292,
)

_TEMPOMESSAGE.fields_by_name['events'].message_type = _EVENT
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['TempoMessage'] = _TEMPOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'tempo_pb2'
  # @@protoc_insertion_point(class_scope:cbiomodels.Event)
  })
_sym_db.RegisterMessage(Event)

TempoMessage = _reflection.GeneratedProtocolMessageType('TempoMessage', (_message.Message,), {
  'DESCRIPTOR' : _TEMPOMESSAGE,
  '__module__' : 'tempo_pb2'
  # @@protoc_insertion_point(class_scope:cbiomodels.TempoMessage)
  })
_sym_db.RegisterMessage(TempoMessage)


# @@protoc_insertion_point(module_scope)
