/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AlleleNumber struct {

	An int32 `json:"an"`

	AnAfr int32 `json:"an_afr"`

	AnAmr int32 `json:"an_amr"`

	AnAsj int32 `json:"an_asj"`

	AnEas int32 `json:"an_eas"`

	AnFin int32 `json:"an_fin"`

	AnNfe int32 `json:"an_nfe"`

	AnOth int32 `json:"an_oth"`

	AnSas int32 `json:"an_sas"`
}
