/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AlleleFrequency struct {

	Af float64 `json:"af"`

	AfAfr float64 `json:"af_afr"`

	AfAmr float64 `json:"af_amr"`

	AfAsj float64 `json:"af_asj"`

	AfEas float64 `json:"af_eas"`

	AfFin float64 `json:"af_fin"`

	AfNfe float64 `json:"af_nfe"`

	AfOth float64 `json:"af_oth"`

	AfSas float64 `json:"af_sas"`
}
