/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Exon struct {

	// Exon id
	ExonId string `json:"exonId"`

	// Start position of exon
	ExonStart int32 `json:"exonStart"`

	// End position of exon
	ExonEnd int32 `json:"exonEnd"`

	// Number of exon in transcript
	Rank int32 `json:"rank"`

	// Strand exon is on, -1 for - and 1 for +
	Strand int32 `json:"strand"`

	// Exon version
	Version int32 `json:"version"`
}
