/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type IndicatorQueryResp struct {

	AlleleExist bool `json:"alleleExist,omitempty"`

	DataVersion string `json:"dataVersion,omitempty"`

	DiagnosticImplications []Implication `json:"diagnosticImplications,omitempty"`

	DiagnosticSummary string `json:"diagnosticSummary,omitempty"`

	GeneExist bool `json:"geneExist,omitempty"`

	GeneSummary string `json:"geneSummary,omitempty"`

	HighestDiagnosticImplicationLevel string `json:"highestDiagnosticImplicationLevel,omitempty"`

	HighestPrognosticImplicationLevel string `json:"highestPrognosticImplicationLevel,omitempty"`

	HighestResistanceLevel string `json:"highestResistanceLevel,omitempty"`

	HighestSensitiveLevel string `json:"highestSensitiveLevel,omitempty"`

	Hotspot bool `json:"hotspot,omitempty"`

	LastUpdate string `json:"lastUpdate,omitempty"`

	MutationEffect *MutationEffectResp `json:"mutationEffect,omitempty"`

	Oncogenic string `json:"oncogenic,omitempty"`

	OtherSignificantResistanceLevels []string `json:"otherSignificantResistanceLevels,omitempty"`

	OtherSignificantSensitiveLevels []string `json:"otherSignificantSensitiveLevels,omitempty"`

	PrognosticImplications []Implication `json:"prognosticImplications,omitempty"`

	PrognosticSummary string `json:"prognosticSummary,omitempty"`

	Query *Query `json:"query,omitempty"`

	Treatments []IndicatorQueryTreatment `json:"treatments,omitempty"`

	TumorTypeSummary string `json:"tumorTypeSummary,omitempty"`

	VariantExist bool `json:"variantExist,omitempty"`

	VariantSummary string `json:"variantSummary,omitempty"`

	Vus bool `json:"vus,omitempty"`
}
