/*
 * Genome Nexus API
 *
 * This page shows how to use HTTP requests to access the Genome Nexus API. There are more high level clients available in Python, R, JavaScript, TypeScript and various other languages as well as a command line client to annotate MAF and VCF. See https://docs.genomenexus.org/api.  Aside from programmatic clients there are web based tools to annotate variants, see https://docs.genomenexus.org/tools.   We currently only provide long-term support for the '/annotation' endpoint. The other endpoints might change.
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TranscriptConsequence struct {

	// Amino acids
	AminoAcids string `json:"amino_acids,omitempty"`

	// Canonical transcript indicator
	Canonical string `json:"canonical,omitempty"`

	// Codons
	Codons string `json:"codons,omitempty"`

	// List of consequence terms
	ConsequenceTerms []string `json:"consequence_terms,omitempty"`

	Exon string `json:"exon,omitempty"`

	// Ensembl gene id
	GeneId string `json:"gene_id,omitempty"`

	// Hugo gene symbol
	GeneSymbol string `json:"gene_symbol,omitempty"`

	// HGNC id
	HgncId string `json:"hgnc_id,omitempty"`

	// HGVSc
	Hgvsc string `json:"hgvsc,omitempty"`

	// HGVSg
	Hgvsg string `json:"hgvsg,omitempty"`

	// HGVSp
	Hgvsp string `json:"hgvsp,omitempty"`

	// Polyphen Prediction
	PolyphenPrediction string `json:"polyphen_prediction,omitempty"`

	// Polyphen Score
	PolyphenScore float64 `json:"polyphen_score,omitempty"`

	// Protein end position
	ProteinEnd int32 `json:"protein_end,omitempty"`

	// Ensembl protein id
	ProteinId string `json:"protein_id,omitempty"`

	// Protein start position
	ProteinStart int32 `json:"protein_start,omitempty"`

	// List of RefSeq transcript ids
	RefseqTranscriptIds []string `json:"refseq_transcript_ids,omitempty"`

	// Sift Prediction
	SiftPrediction string `json:"sift_prediction,omitempty"`

	// Sift Score
	SiftScore float64 `json:"sift_score,omitempty"`

	// Ensembl transcript id
	TranscriptId string `json:"transcript_id"`

	UniprotId string `json:"uniprotId,omitempty"`

	// Variant allele
	VariantAllele string `json:"variant_allele,omitempty"`
}
